// Code generated by entc, DO NOT EDIT.

package project

import (
	"github.com/satriahrh/winslow/ent/schema"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug vertex property in the database.
	FieldSlug = "slug"
	// FieldCurrent holds the string denoting the current vertex property in the database.
	FieldCurrent = "current"

	// Table holds the table name of the project in the database.
	Table = "projects"
	// SprintsTable is the table the holds the sprints relation/edge. The primary key declared below.
	SprintsTable = "project_sprints"
	// SprintsInverseTable is the table name for the Sprint entity.
	// It exists in this package in order to avoid circular dependency with the "sprint" package.
	SprintsInverseTable = "sprints"
	// StoriesTable is the table the holds the stories relation/edge. The primary key declared below.
	StoriesTable = "project_stories"
	// StoriesInverseTable is the table name for the Story entity.
	// It exists in this package in order to avoid circular dependency with the "story" package.
	StoriesInverseTable = "stories"
)

// Columns holds all SQL columns are project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldCurrent,
}

var (
	// SprintsPrimaryKey and SprintsColumn2 are the table columns denoting the
	// primary key for the sprints relation (M2M).
	SprintsPrimaryKey = []string{"project_id", "sprint_id"}
	// StoriesPrimaryKey and StoriesColumn2 are the table columns denoting the
	// primary key for the stories relation (M2M).
	StoriesPrimaryKey = []string{"project_id", "story_id"}
)

var (
	fields = schema.Project{}.Fields()

	// descName is the schema descriptor for name field.
	descName = fields[0].Descriptor()
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = descName.Validators[0].(func(string) error)

	// descSlug is the schema descriptor for slug field.
	descSlug = fields[1].Descriptor()
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator = descSlug.Validators[0].(func(string) error)

	// descCurrent is the schema descriptor for current field.
	descCurrent = fields[2].Descriptor()
	// DefaultCurrent holds the default value on creation for the current field.
	DefaultCurrent = descCurrent.Default.(bool)
)
