// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/satriahrh/winslow/ent/predicate"
	"github.com/satriahrh/winslow/ent/sprint"
)

// SprintDelete is the builder for deleting a Sprint entity.
type SprintDelete struct {
	config
	predicates []predicate.Sprint
}

// Where adds a new predicate to the delete builder.
func (sd *SprintDelete) Where(ps ...predicate.Sprint) *SprintDelete {
	sd.predicates = append(sd.predicates, ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SprintDelete) Exec(ctx context.Context) (int, error) {
	return sd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SprintDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SprintDelete) sqlExec(ctx context.Context) (int, error) {
	spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: sprint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sprint.FieldID,
			},
		},
	}
	if ps := sd.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sd.driver, spec)
}

// SprintDeleteOne is the builder for deleting a single Sprint entity.
type SprintDeleteOne struct {
	sd *SprintDelete
}

// Exec executes the deletion query.
func (sdo *SprintDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{sprint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SprintDeleteOne) ExecX(ctx context.Context) {
	sdo.sd.ExecX(ctx)
}
