// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/satriahrh/winslow/ent/predicate"
	"github.com/satriahrh/winslow/ent/story"
)

// StoryDelete is the builder for deleting a Story entity.
type StoryDelete struct {
	config
	predicates []predicate.Story
}

// Where adds a new predicate to the delete builder.
func (sd *StoryDelete) Where(ps ...predicate.Story) *StoryDelete {
	sd.predicates = append(sd.predicates, ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *StoryDelete) Exec(ctx context.Context) (int, error) {
	return sd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *StoryDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *StoryDelete) sqlExec(ctx context.Context) (int, error) {
	spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: story.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: story.FieldID,
			},
		},
	}
	if ps := sd.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sd.driver, spec)
}

// StoryDeleteOne is the builder for deleting a single Story entity.
type StoryDeleteOne struct {
	sd *StoryDelete
}

// Exec executes the deletion query.
func (sdo *StoryDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{story.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *StoryDeleteOne) ExecX(ctx context.Context) {
	sdo.sd.ExecX(ctx)
}
