// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Sprint is the predicate function for sprint builders.
type Sprint func(*sql.Selector)

// Story is the predicate function for story builders.
type Story func(*sql.Selector)
